# Generated by Django 4.0.3 on 2022-05-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollmembers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
