# Generated by Django 4.0.3 on 2022-04-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_img', models.CharField(max_length=500)),
                ('item_cat', models.CharField(max_length=100)),
                ('votes', models.IntegerField(null=True)),
            ],
        ),
    ]
