# Generated by Django 4.0.3 on 2022-05-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_pollsets_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsets',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
